### ISSUE TITLE
一键脚本里面“Scanning dependencies of target trojan”这一步卡在11%不动

### ISSUE THREAD

**Issue by Lrvineshaw** [maidoudouo/V2ray_Trojan_Docker#1]
系统是ubuntu 18.04 LTS，网络和系统都没问题，特意换了一个VPS测试还是卡在11%

**Comment by maidoudouo** [comment]
![图片](https://user-images.githubusercontent.com/61506664/79062732-55561200-7ccf-11ea-904f-5249f9ed164a.png)
实测没有问题！

**Comment by Lrvineshaw** [comment]
> ![图片](https://user-images.githubusercontent.com/61506664/79062732-55561200-7ccf-11ea-904f-5249f9ed164a.png)
> 实测没有问题！

![优效截图20200415115113](https://user-images.githubusercontent.com/34879145/79296989-760caa80-7f0f-11ea-89c4-7da396e6e752.png)
还是卡在这里，仔细看了一下，我这边5%和11%执行的内容和你的是颠倒的
