### ISSUE TITLE
执行的时候报错

### ISSUE THREAD

**Issue by jindx0713** [maidoudouo/V2ray_Trojan_Docker#4]
[root@jdx V2ray_Trojan_Docker]# docker-compose up -d
Building v2ray
Step 1/15 : FROM ubuntu:19.10 as builder
 ---> 1d654303ff59
Step 2/15 : RUN apt-get update
 ---> Using cache
 ---> 6e7c6b8af8ad
Step 3/15 : RUN apt-get install curl -y
 ---> Running in 647fb471f7fd
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package curl
ERROR: Service 'v2ray' failed to build: The command '/bin/sh -c apt-get install curl -y' returned a non-zero code: 100

**Comment by maidoudouo** [comment]
重试应该就可以了

**Comment by jindx0713** [comment]
在centos下没办法构建成功，只能在Ubuntu下构建。
