### ISSUE TITLE
怎么升级核心程序呢？

### ISSUE THREAD

**Issue by DLGum** [maidoudouo/V2ray_Trojan_Docker#8]
如题。
该怎么升级呢？

**Comment by DLGum** [comment]
重新跑git命令嘛？

**Comment by DLGum** [comment]
好了搞懂了。两步搞定。
cd /root/V2ray_Trojan_Docker
docker-compose up -d

**Comment by maidoudouo** [comment]
可以删除容器和镜像，然后重新docker-compose up -d

**Comment by DLGum** [comment]
> 可以删除容器和镜像，然后重新docker-compose up -d

谢谢。
